function [Hd,F_ECG] = HPF50(signal,Fs,Fs_signal,Fstop,Fpass)
%HPF50 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 10-May-2022 16:55:47

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.

Dstop = 0.1;             % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
flag  = 'scale';         % Sampling Flag
R = Fs_signal/Fs;
% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

h = Hd.Numerator; 
h_new = zeros((length(h) - 1) * R + 1,1); % adding zeros
h_new(1:R:end) = h;
Hd.Numerator = h_new;
F_ECG = filter(Hd,signal);% Changing Filter
% [EOF]
